name: Production

on:
  push:
    branches:
      - release

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: ${{ matrix.app }}
    runs-on: linux-arm64-4vcpu

    strategy:
      fail-fast: false
      matrix:
        app:
          - website
          # - company
          # - help
          # - literoom

    concurrency:
      group: production/${{ matrix.app }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::721144421085:role/actions@github
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: 721144421085.dkr.ecr.ap-northeast-2.amazonaws.com/${{ matrix.app }}
          tags: type=raw,value=latest

      - name: Build image
        uses: docker/build-push-action@v5
        id: build
        with:
          push: true
          context: .
          build-args: |
            APP=${{ matrix.app }}
            TURBO_TEAM=${{ vars.TURBO_TEAM }}
            TURBO_TOKEN=${{ secrets.TURBO_TOKEN }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=721144421085.dkr.ecr.ap-northeast-2.amazonaws.com/${{ matrix.app }}:cache
          cache-to: type=registry,ref=721144421085.dkr.ecr.ap-northeast-2.amazonaws.com/${{ matrix.app }}:cache,mode=max,image-manifest=true
          provenance: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run code generation
        working-directory: apps/${{ matrix.app }}
        run: pnpm exec turbo run codegen
        env:
          TURBO_TEAM: ${{ vars.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: Connect tailnet
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          tags: tag:github-actions

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name penxle

      - name: Apply infrastructure
        uses: pulumi/actions@v5
        with:
          command: up
          work-dir: apps/${{ matrix.app }}
          stack-name: withglyph/prod
          refresh: true
          upsert: true
          config-map: |
            { "withglyph:image.digest": { "value": "${{ steps.build.outputs.digest }}" } }
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_K8S_ENABLE_PATCH_FORCE: 'true'
